### ISSUE TITLE
Passwort variable in README

### ISSUE THREAD

**Issue by TobiGa** [open-lms-open-source/moodle-local_redislock#10]
Hello,
when trying out we noticed in README it says passwort should be saved to $CFG->local_redislock_auth.
It seems _redis_ is missting. Code references local_redislock_redis_auth.
Cheers

**Comment by dvdcastro** [comment]
`$CFG->local_redislock_auth` is a config value which is used by the Moodle plugin to connect to Redis, there should be no mention of it in Redis documentation.

We are setting it as an attribute of the class here:
https://github.com/open-lms-open-source/moodle-local_redislock/blob/master/classes/lock/redis_lock_factory.php#L96

And then we use it to authenticate with `Redis` in the `auth` method. here:
https://github.com/open-lms-open-source/moodle-local_redislock/blob/master/classes/lock/redis_lock_factory.php#L377

More documentation on `auth` can be found here:
https://github.com/phpredis/phpredis#auth
