### ISSUE TITLE
When local_redislock_logging is true, log output finds its way into css generation (and maybe others)

### ISSUE THREAD

**Issue by durzo** [open-lms-open-source/moodle-local_redislock#11]
When `$CFG->local_redislock_logging = true`, we notice the output of Moodle's all css (theme/styles.php/boost/1610979720_1610979812/all) begins with the log output of the redislock plugin, causing css rendering to break as it is invalid css.

**Comment by dvdcastro** [comment]
Holy...

We'll fix ASAP.
